name: Git Version
on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout  
        uses: actions/checkout@v2  
        with:  
            fetch-depth: 0  

      - name: Bump  
        id: bump
        uses: zwaldowski/match-label-action@v4
        with:
          allowed: major,minor,patch

      - name: Version
        uses: zwaldowski/semver-release-action@v3
        with:
          bump: ${{ steps.bump.outputs.match }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
