name: Git Version
on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout  
        uses: actions/checkout@v2  
        with:  
            fetch-depth: 0  

      - name: Version  
        id: version  
        uses: juliansangillo/tag-version@v1  
        with:  
            production-branch: main  
            test-branch: test  
            dev-branch: develop
